### ISSUE TITLE
[build] wlroots issue

### ISSUE THREAD

**Issue by ThomasBucaioni** [stumpwm/mahogany#22]
When running `meson ..`, it gives:
```
heart 0.1

  Subprojects
    wlroots: NO Neither a subproject directory nor a wlroots.wrap file was found.
```
Any idea what went wrong? (Would you have an Irc channel or a place to ask basic questions?)

**Comment by sdilts** [comment]
That probably means that you don't have a wlroots library that can used to build heart installed on your system. If Meson can't find a system-wide wlroots installation, it will look for a directory called `wlroots` in the `heart` directory that contains the wlroots source tree that it will try to compile and use.

So if your distro doesn't have wlroots 0.12 packaged, you can clone the wlroots project into the `heart directory and checkout the tag v0.12.0.

Having wlroots as a git submodule is something I've been meaning to do for a while, so adding it in the source directory would be a good PR.

**Comment by ThomasBucaioni** [comment]
Fixed, maybe it was a version issue...
Regarding having wlroots as a git submodule, it would take to clone the `.h` and `.c` files from there: https://github.com/swaywm/wlroots ? Not being a computer scientist, it would be a bit sloppy to deal with it but I could have a look
