### ISSUE TITLE
Compilation problem : lisp/meson.build missing.

### ISSUE THREAD

**Issue by lidgnulinux** [stumpwm/mahogany#23]
Hello, I'm trying to compile mahogany this morning and I got this error / warning : 

```
heart/meson.build:84:0: ERROR: Non-existent build file 'lisp/meson.build'
```
Is it uncomplete dependencies problem ? I did quicklisp setup before I ran `make`. Thanks.

**Comment by sdilts** [comment]
Sorry about that, that's my bad: there was unfinished work in the repository. It should work once you get the latest change.

**Comment by lidgnulinux** [comment]
Hello, I'm trying it again, but still fail. I got this : 

```
...
While evaluating the form starting at line 16, column 0
  of #P"/home/ahmad/compile/mahogany/build-mahogany.lisp":
Unhandled ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                             {10048F81B3}>:
  Component "mahogany/executable" not found

...
unhandled condition in --disable-debugger mode, quitting
make: *** [Makefile:9: /home/ahmad/compile/mahogany/build/mahogany] Error 1
```

is something wrong with my scbl stuffs ?

**Comment by lidgnulinux** [comment]
Complete build log.
[build.txt](https://github.com/stumpwm/mahogany/files/9421728/build.txt)

**Comment by sdilts** [comment]
Again, this was my fault. This should be fixed up now, and shouldn't happen in the future now that there is a pipeline running for every change.

**Comment by lidgnulinux** [comment]
cl-xkbcommon and cl-wayland are missing, it leads to compilation failure. The solution is simple, just clone them manually and the compilation will success.
